### PR TITLE
Homepage improvements

### PR DESCRIPTION
**Pull request by NotAussie**
# Before
image
image
image

# After
image
image
image

# Checklist
- [x] I have tested this feature locally and it works as expected.
- [ ] ~~I have updated the documentation, if necessary, to reflect the new feature.~~
- [x] I have followed the project's coding standards and best practices.
- [x] I have reviewed my code and ensured it is well-documented and maintainable.
- [ ] I have assigned the pull request to the appropriate reviewer(s).

### CODE REVIEW

**Comment by YumYummity** [comment]
Needs:
- Cat Gifs
- More button padding
- Button size consistency in the second screenshot

**Comment by NotAussie** [comment]
> Needs:
> 
>     * Cat Gifs
> 
>     * More button padding
> 
>     * Button size consistency in the second screenshot

How's this?
image

**Comment by NotAussie** [comment]
Also, the cat gifs don't make sense to be on the page, it makes the page more clunky and adds extra load time.

**Comment by NotAussie** [comment]
**Ready for review :D**

**Review by sohamjaiswal — APPROVED** [review]
lgtm 👍

**Comment by YumYummity** [comment]
noooooo the cat gifs >:(
proposal:
- add cat gifs in settings (if anybody has time), defaulting to OFF

**Pull request merged**
